/*
 * Copyright (c) Johannes Grimm 2024.
 */

//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "plant")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub genetic_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::genetic::Entity",
        from = "Column::GeneticId",
        to = "super::genetic::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Genetic,
}
impl Related<super::genetic::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Genetic.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
